enum TourListPerformanceDisplayType {
  nothing,
  totalWage,
  totalBonus,
  totalWageAndBonus,
  hourlyWageAndBonus,
  maxBonus,
  maxHourlyWageAndBonus,
  workTime,
  workTimeFasterThanPlan,
  plannedTaskCount,
  actualTaskCount,
  plannedAndActualTaskCount,
  percentTaskComplete,
  rating,
  chevron,
  startTime,
}