name: faircare
description: Faircare Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  ars_dialog:
    git:
      url: https://github.com/MubeenNaeem/ars-dialog.git
      ref: master
  dio: ^5.3.3
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  google_maps_flutter: ^2.3.0
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter_xlider: ^3.5.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

scripts:
  p: git push -u fcorigin main