name: faircare
description: Faircare Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  ars_dialog:
    git:
      url: https://github.com/MubeenNaeem/ars-dialog.git
      ref: master
  dio: ^5.3.3
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

scripts:
  p: git push -u origin main